# Generated by Django 5.2.7 on 2025-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration_min',
            field=models.IntegerField(default=45),
        ),
    ]
