# Generated by Django 5.2.7 on 2025-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopDjango', '0002_alter_session_duration_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration_min',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ended_at',
        ),
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
